# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

# Increase network timeouts for slow connections
systemProp.http.proxyHost=
systemProp.http.proxyPort=
systemProp.https.proxyHost=
systemProp.https.proxyPort=
systemProp.http.socketTimeout=600000
systemProp.http.connectionTimeout=600000
systemProp.https.socketTimeout=600000
systemProp.https.connectionTimeout=600000

org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
android.nonTransitiveRClass=true
